### ISSUE TITLE
Wearables - console error spam

### ISSUE THREAD

**Issue by kamild1996** [patkub/tf-sourcemod#1]
My console is being spammed like crazy with these errors:

> L 04/03/2017 - 16:40:49: [SM] Exception reported: Array index is out of bounds
> L 04/03/2017 - 16:40:49: [SM] Blaming: unusual_arrows.smx
> L 04/03/2017 - 16:40:49: [SM] Call stack trace:
> L 04/03/2017 - 16:40:49: [SM]   [1] Line 1031, unusual_arrows.sp::AddParticle
> L 04/03/2017 - 16:40:49: [SM]   [2] Line 1014, unusual_arrows.sp::Unusualify
> L 04/03/2017 - 16:40:49: [SM] Exception reported: Array index is out of bounds

**Comment by patkub** [comment]
@kamild1996 That's an issue with unusual_arrows.smx, not one of my plugins. You should ask in the relative alliedmods forum.

**Comment by kamild1996** [comment]
oh... Ok I'm blind, I didn't even check the plugin name because these errors started appearing as soon as I loaded the wearables plugin. Sorry!
