### ISSUE TITLE
how to install??

### ISSUE THREAD

**Issue by Fogzas** [patkub/tf-sourcemod#3]
please say how to install

**Comment by patkub** [comment]
@Fogzas Install sourcemod, copy desired plugin to scripting, run compile.exe, copy resulting .smx binary to plugins. Optionally, install tf2items extension if you want to use plugins that make use of it.

**Comment by Fogzas** [comment]
No smx file found

**Comment by patkub** [comment]
What plugin are you trying to compile? Any errors under it when running compile.exe? You only need to copy the .sp files to scripting and merge the include folder with to scripting/include

**Comment by Fogzas** [comment]
//// tf2items_wearables.sp
//
// tf2items_wearables.sp(94) : warning 234: symbol "FCVAR_PLUGIN" is marked as deprecated: No logic using this flag ever existed in a released game. It only ever appeared in the first hl2sdk.
//
//
// Code size:            38184 bytes
// Data size:           326044 bytes
// Stack/heap size:      16384 bytes
// Total requirements:  380612 bytes
//
// 1 Warning.
//
// Compilation Time: 0.73 sec

**Comment by patkub** [comment]
Ok, that warning is fine. Copy over the compiled .smx, the configs, and install tf2items extension and tf2idb, see
https://github.com/patkub/tf-sourcemod/blob/master/plugins/tf2items_wearables/README.md

**Comment by Fogzas** [comment]
im have they's

**Comment by Fogzas** [comment]
Not working
Im done with files but is not working
